CREATE TABLE IF NOT EXISTS TASK_CATEGORIES(
    CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR2(500),
    CONSTRAINT TASK_CATEGORIES_PK PRIMARY KEY(CATEGORY_ID),
    CONSTRAINT CATEGORY_NAME_UK UNIQUE(CATEGORY_NAME)
);